Repository jenkinsci/ionicons-api-plugin, pull requests merged in 2022-09, with the labels that each got.

#12 Preview icon additions
  docs/additions.md
Labels: documentation

#16 Provide Java implementation to list available icons
  src/main/java/io/jenkins/plugins/ionicons/Ionicons.java
  src/test/java/io/jenkins/plugins/ionicons/IoniconsTest.java
Labels: enhancement

#17 Fix resource resolution
  src/main/java/io/jenkins/plugins/ionicons/Ionicons.java
Labels: bug

#18 Fix resource resolution of icons in jar file and IDE
  src/main/java/io/jenkins/plugins/ionicons/Ionicons.java
  src/test/java/io/jenkins/plugins/ionicons/IoniconsTest.java
Labels: bug
