Repository jenkinsci/ionicons-api-plugin, pull requests merged in 2022-08, with the labels that each got.

#2 Apply changes from core symbols
  src/main/resources/images/symbols/LICENSE
  src/main/resources/images/symbols/arrow-back.svg
  src/main/resources/images/symbols/arrow-forward.svg
  src/main/resources/images/symbols/arrow-up.svg
  src/main/resources/images/symbols/browsers-outline.svg
  src/main/resources/images/symbols/build-outline.svg
  src/main/resources/images/symbols/close.svg
  src/main/resources/images/symbols/code-slash-outline.svg
  src/main/resources/images/symbols/code-working-outline.svg
  src/main/resources/images/symbols/create-outline.svg
  src/main/resources/images/symbols/finger-print-outline.svg
  src/main/resources/images/symbols/git-branch-outline.svg
  src/main/resources/images/symbols/globe-outline.svg
  src/main/resources/images/symbols/help-circle-outline.svg
  src/main/resources/images/symbols/id-card-outline.svg
  src/main/resources/images/symbols/jenkins.svg
  src/main/resources/images/symbols/lock-closed-outline.svg
  src/main/resources/images/symbols/logo-microsoft.svg
  src/main/resources/images/symbols/logo-rss.svg
  src/main/resources/images/symbols/options-outline.svg
  src/main/resources/images/symbols/people-outline.svg
  src/main/resources/images/symbols/person-circle-outline.svg
  src/main/resources/images/symbols/play-outline.svg
  src/main/resources/images/symbols/power-outline.svg
  src/main/resources/images/symbols/pricetag-outline.svg
  src/main/resources/images/symbols/reload-outline.svg
  src/main/resources/images/symbols/settings-outline.svg
  src/main/resources/images/symbols/timer-outline.svg
Labels: chore

#3 Add info how to use this plugin
  README.md
Labels: documentation

#6 Make `logo-github` theme-able
  src/main/resources/images/symbols/logo-github.svg
Labels: fix

#7 docs: Fix README URLs
  README.md
Labels: documentation

#8 Make youtube, hourglass and radio button theme-able
  src/main/resources/images/symbols/hourglass-outline.svg
  src/main/resources/images/symbols/logo-youtube.svg
  src/main/resources/images/symbols/radio-button-on-outline.svg
Labels: enhancement

#9 fix plugin url
  pom.xml
Labels: bug

#11 Document icon additions
  README.md
  docs/additions.md
  src/main/resources/images/symbols/logo-docker.svg
Labels: enhancement
