Repository jenkinsci/ionicons-api-plugin, pull requests merged in 2023-05, with the labels that each got.

#45 Track extensions.xml and run renovate monthly
  .github/renovate.json
Labels: chore

#44 Add chevrons for collapse and expand
  src/main/resources/images/symbols/chevron-collapse-outline.svg
  src/main/resources/images/symbols/chevron-collapse-sharp.svg
  src/main/resources/images/symbols/chevron-collapse.svg
  src/main/resources/images/symbols/chevron-expand-outline.svg
  src/main/resources/images/symbols/chevron-expand-sharp.svg
  src/main/resources/images/symbols/chevron-expand.svg
Labels: enhancement

#47 Update icons to be themeable
  src/main/resources/images/symbols/chevron-collapse.svg
  src/main/resources/images/symbols/fish-outline.svg
  src/main/resources/images/symbols/flashlight-outline.svg
  src/main/resources/images/symbols/logo-ionic.svg
  src/main/resources/images/symbols/mail-unread-outline.svg
  src/main/resources/images/symbols/train.svg
Labels: bug
